### ISSUE TITLE
大纲的层级太多时行间距过大

### ISSUE THREAD

**Issue by ProMachine** [vanchKong/layout-plugin#2]
大纲的层级太多时行间距过大，还有和行间公式$\display \frac{1}{2}$存在重叠现象

**Comment by ProMachine** [comment]
终于更新了，还有希望在导出的时候也能保留样式

**Comment by vanchKong** [comment]
等我有空研究一下，比较佛系，理解一下🤣

**Comment by ProMachine** [comment]
刚刚发现大纲的层级太多时行间距过大是QYL主题引起的，也可以吸收QYL和其他插件对大纲的自适应处理方式；行间公式$\display \frac{1}{2}$存在重叠的问题似乎没有了；块间隔希望支持多层大纲。

很久之前用过这样一个CSS手动调整，希望整合进自定义间隔里：

```css
.protyle-wysiwyg [data-node-id].li {
	margin: -9px 0px -9px 0px;
}

.b3-list-item__toggle {
	height: 23px;
}

.b3-list-item {
	line-height: 23px;
}
```

**Comment by vanchKong** [comment]
> 块间隔希望支持多层大纲

这个大概是什么样的需求，可以放个图解释一下

**Comment by ProMachine** [comment]
AI给的参考代码如下，试了下，我说的主要是第一条第二条：

```css
/* 1. 调整所有列表块的间距 */
.protyle-wysiwyg [data-node-id].li {
    margin-top: -4px !important;
    margin-bottom: -4px !important;
}

/* 2. 调整嵌套子列表的起始位置 */
.protyle-wysiwyg .li > .list {
    margin-top: -4px !important; /* 防止子级离父级太远 */
    margin-bottom: 5px !important;
}

/* 3. 调整列表内容行的高度和行高 */
.protyle-wysiwyg .b3-list-item {
    min-height: 4px;
    line-height: 24px;
}

/* 4. 修正折叠箭头的垂直居中 */
.protyle-wysiwyg .b3-list-item__toggle {
    height: 24px !important;
}
```
